### ISSUE TITLE
Add Shipped Status to User's Purchase History

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Simple-Shipping#10]
In order to let users know the status of their order, a new column should be added to the purchase history short code that shows whether the order has been shipped.

**Comment by cklosowski** [comment]
With #42, we're showing tracking IDs for items that have them, we'll just need to setup a separate value here for if the item has been shipped.

The end results will be:
1) If the item has been shipped and HAS tracking info, it'll show tracking information
2) If it has been shipped but has NO tracking info, it'll show 'Shipped'
3) If it hasn't been shipped, it'll show a message stating 'Pending Shipping'
4) If the payment does not need shipping, it'll be a `&mdash;`

**Comment by cklosowski** [comment]
![screen shot 2017-02-14 at 4 58 15 pm](https://cloud.githubusercontent.com/assets/1390124/22954965/cc8bbe00-f2d6-11e6-8879-497aff54f6d2.png)

**Comment by pippinsplugins** [comment]
Approved PR but then realized I'd like a change.

Could we change `Pending Shipping` to `Shipment Pending`?

**Comment by cklosowski** [comment]
How's that?

**Comment by pippinsplugins** [comment]
:+1:
