### ISSUE TITLE
Integrate FES with Simple Shipping

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/EDD-Simple-Shipping#12]
We're going to utilize the hooks on the FES order form to add a complete shipping experience for FES users.

**Comment by mindctrl** [comment]
Isn't this finished up already?

**Comment by brashrebel** [comment]
Technically this exists but there's one thing missing: Vendors can set their own international and domestic rates but it will always be based on the _store's_ base country as opposed to the _vendor's_. If vendors are the ones shipping out their own products, it will be necessary to allow vendors to define their own base country and then use that in the checkout calculation.

Should this be a separate issue? I don't see this feature being super useful unless it is some rare use case where the store is actually handling the shipping.

**Comment by pippinsplugins** [comment]
Looks like we never closed the issue.

@brashrebel we already support calculating shipping from the vendor's country. I could have sworn we had setup documentation that showed how to configure vendor country selection but now I cannot find it.

To configure it, just add a country field to vendor profile with the meta key `vendor_country`.

@brashrebel could you get that tested, confirm it still works, then get documentation updated for it?

**Comment by brashrebel** [comment]
✔️ http://docs.easydigitaldownloads.com/article/1905-integration-guide-frontend-submissions-and-simple-shipping

**Comment by pippinsplugins** [comment]
Perfect!
