### ISSUE TITLE
Save shipping address to customer profile

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Simple-Shipping#21]
Mentioned [here](https://easydigitaldownloads.com/forums/topic/saving-shipping-address/) and also in a recent ticket. So I'm just getting the issue started.

**Comment by pippinsplugins** [comment]
@cklosowski could you tackle this sometime soon after you're back?

**Comment by cklosowski** [comment]
:+1:

**Comment by cklosowski** [comment]
I think I'm going to actually save it to a customer meta, and also, this allows us to have multiple shipping addresses for a customer, and can allow them to choose an existing one on checkout, saving time.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
This adds a dropdown to the Shipping Address form of previously used addresses, as well as a 'Add new address' option. This will add the address to the customer record and allow reuse. Customer's can also remove them from their profile editor.

**Comment by pippinsplugins** [comment]
Excellent. Will test early in the week!

**Comment by SDavisMedia** [comment]
@cklosowski Slick UI.

The select menu populated with saved emails addresses is not displaying data from Address Line 2. it's in the database, it just doesn't show the data in the option HTML tag.

Adding a new address is working properly. So is selecting a previously store one. All the address data seems to make it to the merchant processor as well (tested with Stripe). The data displays accurately on the user profile and is removed from the database with the Remove link.

**Comment by SDavisMedia** [comment]
That does it. Everything looking awesome on my end on `issue/21`. :+1:

**Comment by pippinsplugins** [comment]
Looking great!

Could we get some space added after the dropdown?

![screen shot 2017-02-09 at 1 28 44 pm](https://cloud.githubusercontent.com/assets/1034109/22801853/bc85348c-eecb-11e6-9c10-bf2a38cb077e.png)

It's working perfectly.

**Comment by pippinsplugins** [comment]
Oh, not quite. I got a fatal error when trying to run the upgrade routine:

PHP Fatal error: Uncaught Error: Call to undefined method EDD_Simple_Shipping::add_customer_address() in /app/public/wp-content/plugins/edd-simple-shipping/includes/admin/upgrades.php:89

**Comment by SDavisMedia** [comment]
@pippinsplugins I let the display issue slide because it's actually Vendd CSS, not having a bottom margin on a last paragraph within an element. It won't happen in other themes (unless they do the same) and I can fix it in Vendd. As it stands in Simple Shipping, it is correct.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Oh, I renamed that, missed an instance.

**Comment by cklosowski** [comment]
There you go @pippinsplugins fixed the upgrade routine.

**Comment by SDavisMedia** [comment]
Replicated the error during the upgrade routine and the last commit fixes it. But now the upgrade routine nag is persistent.

**Comment by cklosowski** [comment]
It will be until we bump the version constant. Thats the same thing we see
in the EdD upgrade routines. Need to solve something there.

**Comment by SDavisMedia** [comment]
Got it. Then besides that, all is well again on my end. My bad for missing the nag before. Definitely didn't see it.
