### ISSUE TITLE
Prevent new class instances and make static instance accessible.

### ISSUE THREAD

**Issue by tannerm** [easydigitaldownloads/EDD-Simple-Shipping#25]
Currently it is possible to create more than one instance of EDD_Simple_Shipping and there is no way to access the initial instance.

New EDD_Simple_Shipping should be prevented by protecting the __construct function and the original instance should be instantiated with EDD_Simple_Shipping::get_instance() to make it accessible.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
I've been testing this and all things look good. Keep in mind no functionality has changed, this is simple a reorganization. Particularly I want to make sure that the FES integrations work.

**Comment by SDavisMedia** [comment]
`issue/25` is definitely not working with FES at the moment. The Shipping field is removed from the FES submission form and an FES error is thrown on the front end submissions form: 

```
Notice: Outputting using a non FES Field is deprecated. Support will be removed in 2.4. in /Applications/MAMP/htdocs/edd/wp-content/plugins/edd-fes/classes/misc-functions.php on line 681
```

**Comment by cklosowski** [comment]
@SDavisMedia Ok, FES should be fixed up now.

**Comment by SDavisMedia** [comment]
@cklosowski Tried to make sure I'm not missing anything but I seem to be getting the same exact behavior still after pulling down latest `issue/125`. Is it working correctly for you? What version of FES are you on?

**Comment by cklosowski** [comment]
I was testing the FES. I'll have to look into 125.

**Comment by SDavisMedia** [comment]
Everything's looking good for me on `issue/25`. :+1:

Keep in mind that the last commit gave @cklosowski and I different behavior. For him, the default priority of `10` was fine. For me, it was causing the aforementioned error. Changing the priority to `0` works for us both.
