### ISSUE TITLE
Use has_action instead of did_action in has_billing_fields()

### ISSUE THREAD

**Issue by tannerm** [easydigitaldownloads/EDD-Simple-Shipping#26]
has_billing_fields() should call has_action() instead of did_action() to determine whether the specified functions are applied on the specified actions.

**Comment by pippinsplugins** [comment]
`has_action()` would always return `true` (unless someone has removed it). We use `did_action()` in order to detect if the billing address fields have already been added to the checkout.

**Comment by mindctrl** [comment]
I think we can close this. Re-open if you need.

**Comment by tannerm** [comment]
Hrm... must have missed Pippins reply here. I know I had an issue with this but can't remember what it was off the top of my head. I I run into it again I'll re-open with a better description. :)

**Comment by tannerm** [comment]
@pippinsplugins @mindctrl Oh I see what the problem was here. Yeah I was I did remove the `add_action( 'edd_after_cc_fields', 'edd_default_cc_address_fields' )` to remove the billing fields but this function was still returning true. So maybe a combination of has_action and did_action would be better?
