### ISSUE TITLE
Make Shipping fees assign using Price ID

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/EDD-Simple-Shipping#37]
Once issue 4477 in EDD core is resolved, we'll need to make Shipping fees get added to the cart using their price_id. 

https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4477

**Comment by mintplugins** [comment]
PR: https://github.com/easydigitaldownloads/EDD-Simple-Shipping/pull/38

**Comment by pippinsplugins** [comment]
Merged!

**Comment by pippinsplugins** [comment]
And deployed.
