### ISSUE TITLE
Show fully country name in email notification

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Simple-Shipping#41]
A customer has requested that we show the full country name instead of just the country code in the sale notification emails.

https://secure.helpscout.net/conversation/272010715/45819/?folderId=180499

**Comment by SDavisMedia** [comment]
Correct me if I'm wrong but we don't have an email tag at all for the full buyer shipping address. If that's the case, I think we should add a single tag for it.

Similar request: https://secure.helpscout.net/conversation/310048142/51679/?folderId=180499

**Comment by pippinsplugins** [comment]
We do not but I think we should.

**Comment by cklosowski** [comment]
I'll actually open up a separate issue for a new email tag. Since the admin sale notification is the topic here, it's added automatically. A separate email tag can be added later.

**Comment by dgoldak** [comment]
Tested fix. Sales notification email contains full country name.

![screen shot 2018-04-19 at 11 36 13 am](https://user-images.githubusercontent.com/30910807/39005692-7e7e55c8-43c6-11e8-8b39-aa2d4b009dce.png)
