### ISSUE TITLE
Tracking numbers

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Simple-Shipping#42]
We've had a few requests for adding support for tracking numbers. This would include a place to enter the tracking number on orders and to send an email to customers with the tracking number when it is added.

One such request: https://secure.helpscout.net/conversation/282665868/47692/?folderId=180499

I'm not yet sure I want to add this but we should at least consider it.

**Comment by cklosowski** [comment]
I've partially written this as a separate single file plugin. It's really easy to do, and could be pretty beneficial to store owners that are using SS.

**Comment by pippinsplugins** [comment]
Let's do it.

**Comment by cklosowski** [comment]
Ok this is ready for some testing. When a payment needs shipping, we see the following in the View Order Details:
![screen shot 2017-02-02 at 11 10 30 am](https://cloud.githubusercontent.com/assets/1390124/22562511/147284d4-e93a-11e6-8034-9340895ca626.png)

Once tracking IDs have been entered and saved, a `Send Tracking Info` button is shown, which uses the settings here including a new tag `{tracking_ids}`:
![screen shot 2017-02-02 at 11 24 38 am](https://cloud.githubusercontent.com/assets/1390124/22562541/354a35d0-e93a-11e6-9c88-e954b5d51bf1.png)

Looking like this:
![screen shot 2017-02-02 at 11 10 44 am](https://cloud.githubusercontent.com/assets/1390124/22562550/41bcf172-e93a-11e6-87e1-b42ae6a19173.png)

And every time tracking information is sent, we log a payment note:
![screen shot 2017-02-02 at 11 10 53 am](https://cloud.githubusercontent.com/assets/1390124/22562566/58a8e80a-e93a-11e6-8189-d2a42bac7061.png)


On the payment history, the user get's a new column:
![screen shot 2017-02-02 at 11 10 37 am](https://cloud.githubusercontent.com/assets/1390124/22562558/4ba8c7ce-e93a-11e6-80d6-4c0f6d7dbc5e.png)

Clicking the links will take you to 'aftership.com' which is a free tracking service.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs ^^

**Comment by mintplugins** [comment]
Everything looks awesome here. Great UX. 

I didn't get the Tracking email though. The purchase receipt email came in but despite clicking the "Send Tracking Email" several times no email is arriving. I am sending through SendGrid.

**Comment by mintplugins** [comment]
Sending and getting tracking emails now with latest commits. Awesomeness 👍

**Comment by pippinsplugins** [comment]
Can we move the `Send Tracking Info` button to the right side?
![screen shot 2017-02-09 at 1 15 38 pm](https://cloud.githubusercontent.com/assets/1034109/22801404/e6f05be0-eec9-11e6-9c6d-64e2a7a94ab1.png)
I actually didn't see it on my first test of the feature because it was right under the `Add New Tracking ID` button and they blended together.

**Comment by cklosowski** [comment]
Yep!

**Comment by pippinsplugins** [comment]
@cklosowski There's broken PHP at the top of the purchase history row: https://cloudup.com/ckVOEABSWmq

**Comment by cklosowski** [comment]
weird, ok. will look into that.

**Comment by pippinsplugins** [comment]
Also seeing these:

WARNING: wp-includes/class-wp-hook.php:298 - call_user_func_array() expects parameter 1 to be a valid callback, class 'EDD_Simple_Shipping_Tracking' does not have a method 'order_details_row'

NOTICE: wp-content/plugins/edd-simple-shipping/includes/tracking.php:281 - Undefined variable: tracking_ids

**Comment by cklosowski** [comment]
Weird, I'll have to be sure I moved all the new files over.

**Comment by cklosowski** [comment]
@pippinsplugins not even sure what that error means...
because according to this...they should never show like that:
The method deff exists!
https://github.com/easydigitaldownloads/EDD-Simple-Shipping/blob/issue/42/includes/tracking.php#L277

And so does the variable!
https://github.com/easydigitaldownloads/EDD-Simple-Shipping/blob/issue/42/includes/tracking.php#L278

**Comment by cklosowski** [comment]
@pippinsplugins can you pull this all down again, made the changes you wanted, just want to make sure that you weren't missing something in the branch prior

**Comment by pippinsplugins** [comment]
@cklosowski I still see the error on the purchase history template:
![screen shot 2017-02-10 at 12 09 59 pm](https://cloud.githubusercontent.com/assets/1034109/22838240/e39b4e8a-ef89-11e6-9b1b-38321d599e12.png)

**Comment by cklosowski** [comment]
That's really really strange?

![screen shot 2017-02-10 at 11 27 42 am](https://cloud.githubusercontent.com/assets/1390124/22838811/fbcf6870-ef83-11e6-879e-51dd55c5eb21.png)

**Comment by cklosowski** [comment]
Oh I bet I know where it is...one minute.

**Comment by mintplugins** [comment]
I am not seeing that on my Purchase History. 

While I was looking I was wondering if we should remove the tracking column and add it to the View Details and Downloads instead. In twentyseventeen the space is a bit cramped:

<img width="532" alt="screen shot 2017-02-10 at 1 29 48 pm" src="https://cloud.githubusercontent.com/assets/1638128/22838911/39861176-ef95-11e6-9d6b-3bd1dcc5030f.png">

**Comment by cklosowski** [comment]
@pippinsplugins I was wrong. no clue what's causing it.

i'd rather leave it in this space...as it allows us to give a general overview of orders for a customer. I do find it odd that @mintplugins and I get the same results on different themes, but @pippinsplugins  has an issue on Vendd, which is what i'm using. Any other plugins that are adding columns or anything? Something is making a `-` on the table head...and messing with our row data:

What does this method look like on your end? Maybe something accidentally edited?
https://cl.ly/0W450R203c0W/Screen%20Shot%202017-02-10%20at%2011.39.33%20AM.png

**Comment by pippinsplugins** [comment]
Here's what I have:
```php
	/**
	 * Show the 'Tracking' content on the order list.
	 *
	 * @since 2.3
	 *
	 * @return void
	 */
	public function order_details_row( $payment_id, $purchase_data ) {
		$tracking_ids = $this->get_payment_tracking( $payment_id );
		?>
		<td class="edd-order-details-tracking-ids">
			<?php if ( $tracking_ids ) : ?>
				<ul>
				<?php foreach ( $tracking_ids as $tracking_id ) : ?>
					<li><a href="<?php echo $this->get_tracking_link( $tracking_id['tracking_id'] ); ?>" target="_blank"><?php echo $tracking_id['tracking_id']; ?></a></li>
				<?php endforeach; ?>
				</ul>
			<?php else : ?>
				&mdash;
			<?php endif; ?>
		</td>
		<?php
	}
```

**Comment by pippinsplugins** [comment]
I deactivated all other plugins and switched to Twenty Fifteen. Problem still happens.

**Comment by pippinsplugins** [comment]
I still see these warnings too:

WARNING: wp-includes/class-wp-hook.php:298 - call_user_func_array() expects parameter 1 to be a valid callback, class 'EDD_Simple_Shipping_Tracking' does not have a method 'order_details_row'
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/twentyfifteen/page.php'), get_template_part, locate_template, load_template, require('/themes/twentyfifteen/content-page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, do_shortcode, preg_replace_callback, do_shortcode_tag, edd_purchase_history, edd_get_template_part, edd_locate_template, load_template, require('/plugins/easy-digital-downloads/templates/history-purchases.php'), do_action('edd_purchase_history_row_end'), WP_Hook->do_action, WP_Hook->apply_filters

NOTICE: wp-content/plugins/edd-simple-shipping/includes/tracking.php:406 - Undefined variable: tracking_ids
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/twentyfifteen/page.php'), get_template_part, locate_template, load_template, require('/themes/twentyfifteen/content-page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, do_shortcode, preg_replace_callback, do_shortcode_tag, edd_purchase_history, edd_get_template_part, edd_locate_template, load_template, require('/plugins/easy-digital-downloads/templates/history-purchases.php'), do_action('edd_purchase_history_header_after'), WP_Hook->do_action, WP_Hook->apply_filters, EDD_Simple_Shipping_Tracking->order_details_header

**Comment by cklosowski** [comment]
But...as shown above...it does have a method....so....

Chris Klosowski
cklosowski@gmail.com
@cklosowski

On Fri, Feb 10, 2017 at 2:37 PM, Pippin Williamson <notifications@github.com

**Comment by cklosowski** [comment]
Twenty Sixteen. No other items:
![screen shot 2017-02-10 at 2 49 35 pm](https://cloud.githubusercontent.com/assets/1390124/22845508/2e06a71a-efa0-11e6-8750-feaaacad046a.png)

**Comment by SDavisMedia** [comment]
@cklosowski @pippinsplugins I'm not getting a purchase history error in any theme I test. Everything seems fine. Chris, you did or did not replicate?

**Comment by cklosowski** [comment]
@SDavisMedia neither @mintplugins or I can replicate what @pippinsplugins is seeing. He's seeing a PHP Notice, a PHP Warning, and that funky thing in the purchase history.

**Comment by SDavisMedia** [comment]
I can't replicate any of that. The method is clearly there and the variable is defined. I tried to find a scenario that replicates it but I can't.

**Comment by cklosowski** [comment]
Ok moved over the Send Tracking button to the right.

**Comment by pippinsplugins** [comment]
I'll test again.

**Comment by pippinsplugins** [comment]
So weird. This is all fine now. No clue what the issue was before.

Only thing left that I see is too much whitespace below the send notification button:
<img width="1208" alt="screen shot 2017-02-13 at 1 47 42 pm" src="https://cloud.githubusercontent.com/assets/1034109/22900202/1939ec7a-f1f3-11e6-83aa-fd6ca0fdda6a.png">

**Comment by pippinsplugins** [comment]
Oh and one other: column height is inconsistent (may be a Vendd issue):

<img width="948" alt="screen shot 2017-02-13 at 1 48 39 pm" src="https://cloud.githubusercontent.com/assets/1034109/22900234/3aae1570-f1f3-11e6-9d9c-15c471eb2125.png">

**Comment by cklosowski** [comment]
Column height is a theme issue...on TwentySixteen it happens b/c of this:
```
ul, ol {
    margin: 0 0 1.75em 1.25em;
    padding: 0;
}
```

On Vendd it's the same thing:
```
ul, ol {
    margin: 0 0 1.5em 3em;
}
```
![screen shot 2017-02-13 at 1 07 00 pm](https://cloud.githubusercontent.com/assets/1390124/22900929/557108b4-f1ed-11e6-9586-193612d1f2da.png)

**Comment by cklosowski** [comment]
@pippinsplugins converted the front end output to spans with a `block` display, instead of `ul/li`. This is less impact to all the themes.

**Comment by cklosowski** [comment]
![screen shot 2017-02-13 at 1 24 46 pm](https://cloud.githubusercontent.com/assets/1390124/22901715/cd5c3f5e-f1ef-11e6-849e-b32a5ddb26f6.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Cool, Merging if you guys are good then!

**Comment by pippinsplugins** [comment]
Yes
