### ISSUE TITLE
EDD 2.7 - Cart recovery adds two shipping elements

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/EDD-Simple-Shipping#43]
Because of the way that payment recovery system is written, it triggers all previous fees and cart items, but since Simple Shipping runs on `init` at the time, it's adding shipping to the cart again, even though we're adding shipping from a recovered payment.

Simple shipping should see if the shipping fee required is already in the cart before adding it, or have a way to not be activated when the cart recovery is being executed.

Initially I thought maybe we should do this in EDD Core, but I think that sets a bad precedence of fixing other extensions in core.

https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5416

**Comment by cklosowski** [comment]
This fix actually goes beyond `EDD 2.7`, in that when fees are being added, we see if the item already has a shipping charge on it, before adding it.

**Comment by pippinsplugins** [comment]
This change broke shipping fees for variable prices. The fees no longer get added.

I fixed it in https://github.com/easydigitaldownloads/EDD-Simple-Shipping/commit/1e74f845c0ae13fe10e9a7a780d207ff2ecf03bb but that then reverted this fix.

We need to now:

1. Revert back to `edd_get_cart_content_details()`
2. Update the price_id detection to look in the `item_number` array

**Comment by pippinsplugins** [comment]
This should be fixed.

**Comment by pippinsplugins** [comment]
@cklosowski please test to confirm.

**Comment by cklosowski** [comment]
Confirmed, fix is still in place, and no errors.
