### ISSUE TITLE
2.3: Shipping rates do not update properly when switching between New and saved address

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Simple-Shipping#52]
I've found a bug where the domestic / international shipping is not properly updated when entering / selecting the address on checkout.

To replicate:

1. Complete a purchase while logged in with an international address. This address will get saved to your account.
2. Add an item back to your cart and go to checkout.
3. Enter a new _domestic_ address. Do NOT complete the purchase yet. Your shipping rate will be domestic.
4. Pretend you changed your mind and select your stored international address from the dropdown.
5. The shipping rate should update to international but it does not

Essentially, shipping rate changes do not work properly when changing an address by selecting a stored address.

**Comment by cklosowski** [comment]
Issue is primary the new 'stored shipping addresses'. We just need to update the JS to listen to the new 'Store Addresses' field added in #21

**Comment by SDavisMedia** [comment]
Replicated on `master` and confirmed fixed on `issue/52`. :+1:
