### ISSUE TITLE
2.3: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Simple-Shipping#55]
Simple Shipping triggers the following warning on the FES `Orders` tab of the vendor dashboard:

call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

Full stack:

do_action('fes-order-table-column-title')
wp-content/plugins/edd-fes/templates/frontend-orders.php:12
load_template('/wp-content/plugins/edd-fes/templates/frontend-orders.php')
wp-content/plugins/edd-fes/classes/frontend/class-templates.php:154
FES_Templates->fes_locate_template()
wp-content/plugins/edd-fes/classes/frontend/class-templates.php:111
FES_Templates->fes_get_template_part()
wp-content/plugins/edd-fes/classes/frontend/class-dashboard.php:197
FES_Dashboard->display_fes_dashboard()
wp-includes/shortcodes.php:345
do_shortcode_tag()
Unknown location
preg_replace_callback()
wp-includes/shortcodes.php:223
do_shortcode()
wp-includes/class-wp-hook.php:298
apply_filters('the_content')
wp-includes/post-template.php:240
the_content()
wp-content/themes/twentytwelve/content-page.php:20
load_template('/wp-content/themes/twentytwelve/content-page.php')
wp-includes/template.php:643
locate_template()
wp-includes/general-template.php:167
get_template_part('content','page')
wp-content/themes/twentytwelve/page.php:21

See https://github.com/easydigitaldownloads/edd-fes/issues/1174#issuecomment-284632662

**Comment by cklosowski** [comment]
Turns out the front end vendor view that integrated with Simple Shipping was trying ot use a value that was registered for when the user is in the admin, but since it's front end, that would ahve been false.

In the restructure, we isolated code between front end and admin, which caused this.

Will find a work around.
