### ISSUE TITLE
Simple shipping error on account page

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Simple-Shipping#64]
Getting this error on the simple shipping account page:

<img width="962" alt="screenshot 2017-07-05 17 23 17" src="https://user-images.githubusercontent.com/22668877/27874226-b7810e90-61a6-11e7-81e0-d80dcdeb8b3b.png">

**Comment by pippinsplugins** [comment]
Weird . . . I saw this originally when we were working on https://github.com/easydigitaldownloads/EDD-Simple-Shipping/issues/42#issuecomment-279020906. No idea yet what causes it.

**Comment by cklosowski** [comment]
I believe we fixed this already, in #67 Closing until it rears it's ugly head again.
