### ISSUE TITLE
Mark Payment as Shipped from Payment History

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Simple-Shipping#7]
To expedite the completion process, being able to mark an item as shipped from Payment History would be excellent.

**Comment by cklosowski** [comment]
We added this to the bulk actions list already:
<img width="241" alt="screen shot 2018-03-19 at 11 12 12 am" src="https://user-images.githubusercontent.com/1390124/37613894-6af0b9ec-2b66-11e8-87a3-fe1f331427e2.png">

Going to close this for now until it get's asked for again. Now that we've added support for the shipment tracking, there is more to 'simple shipping' than just marking it as shipped.
