### ISSUE TITLE
Changing of shipping address can allow clicking complete purchase before shipping has been recalculated.

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/EDD-Simple-Shipping#74]
Customer reported that their customer was charged domestic shipping when international shipping should have been charged.

![capture1](https://user-images.githubusercontent.com/30910807/37989407-fde0efa2-31c8-11e8-9267-cc68aac74fd5.GIF)
![capture2](https://user-images.githubusercontent.com/30910807/37989414-014fcf78-31c9-11e8-9f06-8b229ce534e3.GIF)

I tested on their site using the same address in the screenshot and was able to see the same behavior when sent to PayPal. Customer site: http://thirteenthnoterecords.com/west-coast-trio

But testing on my test site and the customers site again, I was unable to recreate until I realized when you change the country the total changes briefly. See video in this .zip file:
[Total Calculation Delay.zip](https://github.com/easydigitaldownloads/EDD-Simple-Shipping/files/1853448/Total.Calculation.Delay.zip)

I figured out if you click purchase quick enough after changing the country the wrong price will get sent to PayPal. If you wait a couple seconds for the total to update, it correct price is sent.

I was unable to recreate this behavior on a test system, so I'm not sure if there is something unique with the customer's site?

https://secure.helpscout.net/conversation/548833379/79126?folderId=180499

**Comment by cklosowski** [comment]
I think the right solution here is to make the complete purchase button disabled while that state change is happening.

**Comment by cklosowski** [comment]
Got this working, as @dgoldak stated, it's super hard to test locally b/c of the speed of the AJAX request, but slowing it down in the Chrome Network utility to `Slow 3G` seems to work. Also, keep in mind that the color/view/state of the button may not change, due to styling.

**Comment by cklosowski** [comment]
Updated the issue title to reflect the issue, instead of the symptom.

**Comment by dgoldak** [comment]
@cklosowski when testing, how do yo know the Purchase button is disabled? I'm not able to reproduce the wrong shipping fee so it appears to be working. But to confirm, is it expected I can click Checkout while the button is disabled and it proceed to the Purchase Conformation without clicking the button again (when it's no longer disabled).

**Comment by cklosowski** [comment]
@dgoldak I was using the chrome/Firefox dev tools to inspect the element. It was changing so fast I never saw the `disabled` but when I slowed it down artificially, i saw it. In the inspector, items that are modified turn a different color (whole line turns yellow in FF, and the opening tag turns purple in Chrome) and then fade back to white:

![](https://cl.ly/3Y1l3V1M2h0s/Screen%20Recording%202018-04-19%20at%2009.36%20AM.gif)

**Comment by cklosowski** [comment]
Depending on the theme, the button might change color (that's up to the themes to style `disabled` elements), but while the `disabled` attribute is on the button, it cannot be clicked.

**Comment by dgoldak** [comment]
@cklosowski I confirmed I see the purple box appear behind the opening tag (input) when the country is changed. This looks good to me!
