### ISSUE TITLE
Include Simple Shipping customer addresses to WP Core data export

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/EDD-Simple-Shipping#75]
## Enhancement Request
Simple Shipping needs to be able to provide shipping addresses associated with a customer with a provided email address.

### Justification or use case
This is a [GDPR](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6216) issue.

**Comment by SDavisMedia** [comment]
Attempted to test this but ran into a problem where the shipping address was not saved on the customer record. `ss_upgrade_customer_addresses` appeared to have run in the past but I don't remember running it. I cleared it from my completed upgrades and got the nag back, but initiating the upgrade doesn't seem to work. The page just refreshes.

So I'm gonna continue testing related GDPR functionality and come back to this. @cklosowski, you mentioned in Slack that you'll take a look at the upgrade routine and see if there's a problem with it. Once you do that, I'll definitely try again. Thanks!

**Comment by SDavisMedia** [comment]
Actually, if there was an upgrade routine to move shipping addresses to customer meta, shouldn't new shipping purchases automatically save the shipping address to the customer meta?

I may be missing something. I'm on EDD `master` and SS `issue/75`.

**Comment by SDavisMedia** [comment]
Scratch literally everything I've said. Customer Shipping Addresses is in the export just fine after running the upgrade routine again. I guess part of the routine is broken to where it doesn't clear the nag or update `edd_completed_notices`. But the data is in the export now as it should be. :+1:
